### ISSUE TITLE
Calibre版本7.2安装失败

### ISSUE THREAD

**Issue by lvxiaohao** [DoiiarX/NLCISBNPlugin#1]
calibre, version 7.2.0
错误： 未处理的异常: <b>InvalidPlugin</b>:The plugin in 'D:\\Download\\NLCISBNPlugin-1.0.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 7.2  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'D:\\Download\\NLCISBNPlugin-1.0.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by tychoon** [comment]
找不到zip文件下载的地方啊……从这里选zip下载的安装插件时就报上面的错，下载v1.0.0的也报上面的错，到底怎么下载才是正确的文件？为什么非要搞到那么复杂一定要技术佬才会用呢？直接提供个正确的zip文件有多难呢？
<img width="421" alt="截屏2024-01-05 11 27 41" src="https://github.com/DoiiarX/NLCISBNPlugin/assets/5457353/6b49aad9-2cb5-431e-844d-4f5c489c7e12">

**Comment by DoiiarX** [comment]
> 找不到zip文件下载的地方啊……从这里选zip下载的安装插件时就报上面的错，下载v1.0.0的也报上面的错，到底怎么下载才是正确的文件？为什么非要搞到那么复杂一定要技术佬才会用呢？直接提供个正确的zip文件有多难呢？
> <img width="421" alt="截屏2024-01-05 11 27 41" src="https://github.com/DoiiarX/NLCISBNPlugin/assets/5457353/6b49aad9-2cb5-431e-844d-4f5c489c7e12">
> 

一般在releases那里下载打包好的文件，你下载的zip文件的地方是用来clone代码的。

你直接从下面的地址下载吧。

https://github.com/DoiiarX/NLCISBNPlugin/releases/download/nlcisbn-2024-01-04-1028/NLCISBNPlugin.zip

**Comment by tychoon** [comment]
谢大佬提供下载链接！顺便问一句，正常下载的话在哪里找呢？

**Comment by DoiiarX** [comment]
> 谢大佬提供下载链接！顺便问一句，正常下载的话在哪里找呢？

releases这里啊

![IMG_20240111_231441.jpg](https://github.com/DoiiarX/NLCISBNPlugin/assets/25550075/0018fecd-43ab-43e8-ad91-a36c2e529707)
