### ISSUE TITLE
请问将来能否支持中国国家版本馆的数据呢？

### ISSUE THREAD

**Issue by fuhao3503** [DoiiarX/NLCISBNPlugin#12]
https://pdc.capub.cn/
中国国家版本馆的数据，我自己根据手头图书查找的结果，感觉比中国国家图书馆要好的多。
所以冒昧问一下，将来能否支持中国国家版本馆的数据呢？
谢谢!

**Comment by DoiiarX** [comment]
可以加入开发计划。

**Comment by DoiiarX** [comment]
需要登录。等周末时间长了我再开发吧。

**Comment by DoiiarX** [comment]
![image](https://github.com/user-attachments/assets/f7f05f90-4d25-42b7-8784-b939ee7f86ec)
这个一般怎么解决？这个似乎只有十条。

**Comment by DoiiarX** [comment]
Q群 491708665
