### ISSUE TITLE
请问能不能在网页一键获取图书信息呢？

### ISSUE THREAD

**Issue by Wan200007** [DoiiarX/NLCISBNPlugin#14]
比如说在图书馆馆藏目录搜索某个主题的书，跳出书的结果以后，可以一键把该书的书名、作者、出版社等信息导出成excel？

**Comment by DoiiarX** [comment]
我代码是能做到的。唯一问题是，calilbre插件导出excel我好像没弄过。

**Comment by DoiiarX** [comment]
已列入两周内开发计划

**Comment by DoiiarX** [comment]
https://chromewebstore.google.com/detail/crawlemon/omhiddaacemadihfgbdmpioljgfhddkp?hl=zh-CN

已经完成。Crawlemon一键导出页面数据。
