### ISSUE TITLE
当单一isbn对应多本书籍时，无法下载元数据

### ISSUE THREAD

**Issue by bigmouse0001** [DoiiarX/NLCISBNPlugin#4]
![image](https://github.com/DoiiarX/NLCISBNPlugin/assets/119995454/3712cb6c-7f68-4412-8618-2149c8efd587)

有点疑惑，这个不需要登录国图账号获取cookie吗？？

**Comment by DoiiarX** [comment]
1. 今天太晚了，晚点修复这个bug。
2. 这个bug的原因是，该isbn `9787020050338
`指向的“鲁迅全集”，鲁迅全集有非常多卷，一个isbn对应多本书。而目前插件只支持isbn唯一对应的书籍。
3.该bug会在我添加“根据书名模糊搜索”功能之后修复。
4.该插件不需要用户手动获取cookies。国图主要的阻止方式是会动态生成一个访问地址，这个问题我在代码开头已经解决了。
5.如果需要，我可能会在爬虫中添加自动获取cookies的代码。

**Comment by bigmouse0001** [comment]
> 1. 今天太晚了，晚点修复这个bug。
> 2. 这个bug的原因是，该isbn `9787020050338
> `指向的“鲁迅全集”，鲁迅全集有非常多卷，一个isbn对应多本书。而目前插件只支持isbn唯一对应的书籍。
> 3. 该bug会在我添加“根据书名模糊搜索”功能之后修复。
> 4. 该插件不需要用户手动获取cookies。国图主要的阻止方式是会动态生成一个访问地址，这个问题我在代码开头已经解决了。
> 5. 如果需要，我可能会在爬虫中添加自动获取cookies的代码。

感谢回复，建议支持"根据书名+作者+年份"精确搜索，因为同时搜索上述三个关键词就能确定具体书籍了

**Comment by bigmouse0001** [comment]
> 1. 今天太晚了，晚点修复这个bug。
> 2. 这个bug的原因是，该isbn `9787020050338
> `指向的“鲁迅全集”，鲁迅全集有非常多卷，一个isbn对应多本书。而目前插件只支持isbn唯一对应的书籍。
> 3. 该bug会在我添加“根据书名模糊搜索”功能之后修复。
> 4. 该插件不需要用户手动获取cookies。国图主要的阻止方式是会动态生成一个访问地址，这个问题我在代码开头已经解决了。
> 5. 如果需要，我可能会在爬虫中添加自动获取cookies的代码。

感谢回复，建议支持"根据书名+作者+年份"精确搜索，因为同时搜索上述三个关键词就能确定具体书籍了

**Comment by DoiiarX** [comment]
> ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> 
> 有点疑惑，这个不需要登录国图账号获取cookie吗？？

修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。

被下面这句话搞疯了

Merging results from different sources 
We have 1 merged results, merging took: 0.00 seconds

**Comment by bigmouse0001** [comment]
> > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > 
> > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> 
> 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> 
> 被下面这句话搞疯了
> 
> Merging results from different sources 
> We have 1 merged results, merging took: 0.00 seconds 

下载元数据的时候，只要isbn相同就会被calibre自动合并吗？？

**Comment by DoiiarX** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> > 
> > 
> > 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> > 被下面这句话搞疯了
> > Merging results from different sources
> > We have 1 merged results, merging took: 0.00 seconds
> 
> 下载元数据的时候，只要isbn相同的多个条目就会被calibre自动合并为单个条目吗？

看起来是这样子，而且没有isbn值的，例如按标题搜索，也直接就合并成一个了

**Comment by bigmouse0001** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > > > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> > > 
> > > 
> > > 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> > > 被下面这句话搞疯了
> > > Merging results from different sources
> > > We have 1 merged results, merging took: 0.00 seconds
> > 
> > 下载元数据的时候，只要isbn相同的多个条目就会被calibre自动合并为单个条目吗？
> 
> 看起来是这样子，而且没有isbn值的，例如按标题搜索，也直接就合并成一个了

。。。那这个就有点难办了，这是calibre的逻辑问题

如果无法解决，是否能在calibre之外，直接将元数据写入pdf呢？

**Comment by DoiiarX** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > > > > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> > > > 
> > > > 
> > > > 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> > > > 被下面这句话搞疯了
> > > > Merging results from different sources
> > > > We have 1 merged results, merging took: 0.00 seconds
> > > 
> > > 
> > > 下载元数据的时候，只要isbn相同的多个条目就会被calibre自动合并为单个条目吗？
> > 
> > 
> > 看起来是这样子，而且没有isbn值的，例如按标题搜索，也直接就合并成一个了
> 
> 。。。那这个就有点难办了，这是calibre的逻辑问题
> 
> 如果无法解决，是否能在calibre之外，直接将search到的元数据写入pdf呢？
> 
> 事实上calibre自带的ebook-meta就有往pdf写入元数据的功能，元数据写入pdf之后，导入calibre的条目就自带元数据了，等于最终效果一样的。
> 
> 而且豆瓣上目前也有一个非常好的douban calibre api脚本https://github.com/acdzh/douban-book-api
![image](https://github.com/DoiiarX/NLCISBNPlugin/assets/25550075/f79b9823-0f77-42d4-90b5-0e303da119e8)

两年前我就实现了这个功能，但是我没有优化针对多个书籍元数据候选项的情况。

**Comment by DoiiarX** [comment]
> ![image](https://private-user-images.githubusercontent.com/25550075/296782887-70203c45-95d5-4060-b7ac-63e21994faf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDg3ODQsIm5iZiI6MTcwNTQwODQ4NCwicGF0aCI6Ii8yNTU1MDA3NS8yOTY3ODI4ODctNzAyMDNjNDUtOTVkNS00MDYwLWI3YWMtNjNlMjE5OTRmYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2VmZmZlMzk5YjE1YTdiY2UyY2EyNmI5MTU2NTlmODBhMGE3ZjJkNzkxNzliYTI4YTU3Njg1OTFlZGM0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1mmtAdfNtGeyRlSwsXcjLNXPeps0L-Rc4R_LlPGgO8)
> 
> > > > > > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > > > > > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> > > > > 
> > > > > 
> > > > > 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> > > > > 被下面这句话搞疯了
> > > > > Merging results from different sources
> > > > > We have 1 merged results, merging took: 0.00 seconds
> > > > 
> > > > 
> > > > 下载元数据的时候，只要isbn相同的多个条目就会被calibre自动合并为单个条目吗？
> > > 
> > > 
> > > 看起来是这样子，而且没有isbn值的，例如按标题搜索，也直接就合并成一个了
> > 
> > 
> > 。。。那这个就有点难办了，这是calibre的逻辑问题
> > 如果无法解决，是否能在calibre之外，直接将search到的元数据写入pdf呢？
> > 事实上calibre自带的ebook-meta就有往pdf写入元数据的功能，元数据写入pdf之后，导入calibre的条目就自带元数据了，等于最终效果一样的。
> > 而且豆瓣上目前也有一个非常好的douban calibre api脚本https://github.com/acdzh/douban-book-api
> 
> ![image](https://private-user-images.githubusercontent.com/25550075/296782931-a8410f83-c70c-4fb3-95fb-7424b64b2173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDg3ODQsIm5iZiI6MTcwNTQwODQ4NCwicGF0aCI6Ii8yNTU1MDA3NS8yOTY3ODI5MzEtYTg0MTBmODMtYzcwYy00ZmIzLTk1ZmItNzQyNGI2NGIyMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMjQzMjIxZjFhZWE4YjgzZmNmNTYwYTQ0M2MxYmNlNGQwY2NhMzc1YjJmNTBlNmU3ZGQ5ZDJhNzQ2OWYwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8iSVdMdE2rBc6JHzc2L_WXatCHpViA-IVVEsdP2RSM)
> 
> 研究出来原理了，这个问题解决了，今天太晚了，晚点更新。

速度太快，被封IP了。。。再鸽下去。

**Comment by bigmouse0001** [comment]
> > ![image](https://private-user-images.githubusercontent.com/25550075/296782887-70203c45-95d5-4060-b7ac-63e21994faf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDg3ODQsIm5iZiI6MTcwNTQwODQ4NCwicGF0aCI6Ii8yNTU1MDA3NS8yOTY3ODI4ODctNzAyMDNjNDUtOTVkNS00MDYwLWI3YWMtNjNlMjE5OTRmYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2VmZmZlMzk5YjE1YTdiY2UyY2EyNmI5MTU2NTlmODBhMGE3ZjJkNzkxNzliYTI4YTU3Njg1OTFlZGM0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1mmtAdfNtGeyRlSwsXcjLNXPeps0L-Rc4R_LlPGgO8)
> > 
> > > > > > > ![image](https://private-user-images.githubusercontent.com/119995454/293953315-3712cb6c-7f68-4412-8618-2149c8efd587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDM4MjUsIm5iZiI6MTcwNDU0MzUyNSwicGF0aCI6Ii8xMTk5OTU0NTQvMjkzOTUzMzE1LTM3MTJjYjZjLTdmNjgtNDQxMi04NjE4LTIxNDljOGVmZDU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjE4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTk3YmRmNDE3MzYwOGRjOTNkNGNmZDJiOWQwMDViYTY1NzAwN2JlMzg0YTBkOGY5MTI0M2Q0OGQwZmM1MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M9YdCpYpyc05FAmbd5xx_9ZQEGBNKlgLrOVEmOZpD7c)
> > > > > > > 有点疑惑，这个不需要登录国图账号获取cookie吗？？
> > > > > > 
> > > > > > 
> > > > > > 修复这个bug异常的难。一旦获取多个元数据，又会被系统自动合并。经常八个数据项只剩下一个。仍然在修复bug中。
> > > > > > 被下面这句话搞疯了
> > > > > > Merging results from different sources
> > > > > > We have 1 merged results, merging took: 0.00 seconds
> > > > > 
> > > > > 
> > > > > 下载元数据的时候，只要isbn相同的多个条目就会被calibre自动合并为单个条目吗？
> > > > 
> > > > 
> > > > 看起来是这样子，而且没有isbn值的，例如按标题搜索，也直接就合并成一个了
> > > 
> > > 
> > > 。。。那这个就有点难办了，这是calibre的逻辑问题
> > > 如果无法解决，是否能在calibre之外，直接将search到的元数据写入pdf呢？
> > > 事实上calibre自带的ebook-meta就有往pdf写入元数据的功能，元数据写入pdf之后，导入calibre的条目就自带元数据了，等于最终效果一样的。
> > > 而且豆瓣上目前也有一个非常好的douban calibre api脚本https://github.com/acdzh/douban-book-api
> > 
> > ![image](https://private-user-images.githubusercontent.com/25550075/296782931-a8410f83-c70c-4fb3-95fb-7424b64b2173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDg3ODQsIm5iZiI6MTcwNTQwODQ4NCwicGF0aCI6Ii8yNTU1MDA3NS8yOTY3ODI5MzEtYTg0MTBmODMtYzcwYy00ZmIzLTk1ZmItNzQyNGI2NGIyMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEyMzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMjQzMjIxZjFhZWE4YjgzZmNmNTYwYTQ0M2MxYmNlNGQwY2NhMzc1YjJmNTBlNmU3ZGQ5ZDJhNzQ2OWYwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8iSVdMdE2rBc6JHzc2L_WXatCHpViA-IVVEsdP2RSM)
> > 
> > 研究出来原理了，这个问题解决了，今天太晚了，晚点更新。
> 
> 速度太快，被封IP了。。。再鸽下去。

汗，慢慢弄，不着急

**Comment by DoiiarX** [comment]
你重新试一试。插件更新了。
