### ISSUE TITLE
元数据录入优化

### ISSUE THREAD

**Issue by vlate** [DoiiarX/NLCISBNPlugin#8]
希望开发者能优化一下元数据的录入内容：
1.简化书名信息，去掉原数据中的"文献类型"、“英文名称”、“作者”等。
2.优化作者字段，去掉“著”字，这会影响calibre书库目录名称。
3.优化标签字段，将出版社、出版年等信息移入calibre原出版商、出版日期字段。
4.优化标识符字段，nlchash数据似乎没什么用，希望移除。
5.另，优化书名模糊搜索，基本上没有isbn的情况下没有结果。
<img width="374" alt="屏幕截图 2024-02-09 170935" src="https://github.com/DoiiarX/NLCISBNPlugin/assets/37984211/444d751e-5f00-4511-872a-a6aa5996b4d3">

**Comment by DoiiarX** [comment]
https://github.com/DoiiarX/NLCISBNPlugin/pull/9

已完成
